"""create users table

Revision ID: 9d6b55dae54f
Revises: 
Create Date: 2026-02-04 14:37:44.239565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6b55dae54f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_users',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('id_max', sa.Integer(), nullable=False),
    sa.Column('pcode', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('midname', sa.String(length=255), nullable=True),
    sa.Column('bdate', sa.String(length=32), nullable=False),
    sa.Column('cllogin', sa.String(length=255), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registered_users_id_max'), 'registered_users', ['id_max'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registered_users_id_max'), table_name='registered_users')
    op.drop_table('registered_users')
    # ### end Alembic commands ###
